package com.jia.changle.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ClCommentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cl_comment
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cl_comment
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cl_comment
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_comment
     *
     * @mbggenerated
     */
    public ClCommentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_comment
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_comment
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_comment
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_comment
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_comment
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_comment
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_comment
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_comment
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_comment
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_comment
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cl_comment
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCommentIdIsNull() {
            addCriterion("comment_id is null");
            return (Criteria) this;
        }

        public Criteria andCommentIdIsNotNull() {
            addCriterion("comment_id is not null");
            return (Criteria) this;
        }

        public Criteria andCommentIdEqualTo(Integer value) {
            addCriterion("comment_id =", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdNotEqualTo(Integer value) {
            addCriterion("comment_id <>", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdGreaterThan(Integer value) {
            addCriterion("comment_id >", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("comment_id >=", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdLessThan(Integer value) {
            addCriterion("comment_id <", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdLessThanOrEqualTo(Integer value) {
            addCriterion("comment_id <=", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdIn(List<Integer> values) {
            addCriterion("comment_id in", values, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdNotIn(List<Integer> values) {
            addCriterion("comment_id not in", values, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdBetween(Integer value1, Integer value2) {
            addCriterion("comment_id between", value1, value2, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("comment_id not between", value1, value2, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentUserIsNull() {
            addCriterion("comment_user is null");
            return (Criteria) this;
        }

        public Criteria andCommentUserIsNotNull() {
            addCriterion("comment_user is not null");
            return (Criteria) this;
        }

        public Criteria andCommentUserEqualTo(String value) {
            addCriterion("comment_user =", value, "commentUser");
            return (Criteria) this;
        }

        public Criteria andCommentUserNotEqualTo(String value) {
            addCriterion("comment_user <>", value, "commentUser");
            return (Criteria) this;
        }

        public Criteria andCommentUserGreaterThan(String value) {
            addCriterion("comment_user >", value, "commentUser");
            return (Criteria) this;
        }

        public Criteria andCommentUserGreaterThanOrEqualTo(String value) {
            addCriterion("comment_user >=", value, "commentUser");
            return (Criteria) this;
        }

        public Criteria andCommentUserLessThan(String value) {
            addCriterion("comment_user <", value, "commentUser");
            return (Criteria) this;
        }

        public Criteria andCommentUserLessThanOrEqualTo(String value) {
            addCriterion("comment_user <=", value, "commentUser");
            return (Criteria) this;
        }

        public Criteria andCommentUserLike(String value) {
            addCriterion("comment_user like", value, "commentUser");
            return (Criteria) this;
        }

        public Criteria andCommentUserNotLike(String value) {
            addCriterion("comment_user not like", value, "commentUser");
            return (Criteria) this;
        }

        public Criteria andCommentUserIn(List<String> values) {
            addCriterion("comment_user in", values, "commentUser");
            return (Criteria) this;
        }

        public Criteria andCommentUserNotIn(List<String> values) {
            addCriterion("comment_user not in", values, "commentUser");
            return (Criteria) this;
        }

        public Criteria andCommentUserBetween(String value1, String value2) {
            addCriterion("comment_user between", value1, value2, "commentUser");
            return (Criteria) this;
        }

        public Criteria andCommentUserNotBetween(String value1, String value2) {
            addCriterion("comment_user not between", value1, value2, "commentUser");
            return (Criteria) this;
        }

        public Criteria andCommentEmailIsNull() {
            addCriterion("comment_email is null");
            return (Criteria) this;
        }

        public Criteria andCommentEmailIsNotNull() {
            addCriterion("comment_email is not null");
            return (Criteria) this;
        }

        public Criteria andCommentEmailEqualTo(String value) {
            addCriterion("comment_email =", value, "commentEmail");
            return (Criteria) this;
        }

        public Criteria andCommentEmailNotEqualTo(String value) {
            addCriterion("comment_email <>", value, "commentEmail");
            return (Criteria) this;
        }

        public Criteria andCommentEmailGreaterThan(String value) {
            addCriterion("comment_email >", value, "commentEmail");
            return (Criteria) this;
        }

        public Criteria andCommentEmailGreaterThanOrEqualTo(String value) {
            addCriterion("comment_email >=", value, "commentEmail");
            return (Criteria) this;
        }

        public Criteria andCommentEmailLessThan(String value) {
            addCriterion("comment_email <", value, "commentEmail");
            return (Criteria) this;
        }

        public Criteria andCommentEmailLessThanOrEqualTo(String value) {
            addCriterion("comment_email <=", value, "commentEmail");
            return (Criteria) this;
        }

        public Criteria andCommentEmailLike(String value) {
            addCriterion("comment_email like", value, "commentEmail");
            return (Criteria) this;
        }

        public Criteria andCommentEmailNotLike(String value) {
            addCriterion("comment_email not like", value, "commentEmail");
            return (Criteria) this;
        }

        public Criteria andCommentEmailIn(List<String> values) {
            addCriterion("comment_email in", values, "commentEmail");
            return (Criteria) this;
        }

        public Criteria andCommentEmailNotIn(List<String> values) {
            addCriterion("comment_email not in", values, "commentEmail");
            return (Criteria) this;
        }

        public Criteria andCommentEmailBetween(String value1, String value2) {
            addCriterion("comment_email between", value1, value2, "commentEmail");
            return (Criteria) this;
        }

        public Criteria andCommentEmailNotBetween(String value1, String value2) {
            addCriterion("comment_email not between", value1, value2, "commentEmail");
            return (Criteria) this;
        }

        public Criteria andCommentAddressIsNull() {
            addCriterion("comment_address is null");
            return (Criteria) this;
        }

        public Criteria andCommentAddressIsNotNull() {
            addCriterion("comment_address is not null");
            return (Criteria) this;
        }

        public Criteria andCommentAddressEqualTo(String value) {
            addCriterion("comment_address =", value, "commentAddress");
            return (Criteria) this;
        }

        public Criteria andCommentAddressNotEqualTo(String value) {
            addCriterion("comment_address <>", value, "commentAddress");
            return (Criteria) this;
        }

        public Criteria andCommentAddressGreaterThan(String value) {
            addCriterion("comment_address >", value, "commentAddress");
            return (Criteria) this;
        }

        public Criteria andCommentAddressGreaterThanOrEqualTo(String value) {
            addCriterion("comment_address >=", value, "commentAddress");
            return (Criteria) this;
        }

        public Criteria andCommentAddressLessThan(String value) {
            addCriterion("comment_address <", value, "commentAddress");
            return (Criteria) this;
        }

        public Criteria andCommentAddressLessThanOrEqualTo(String value) {
            addCriterion("comment_address <=", value, "commentAddress");
            return (Criteria) this;
        }

        public Criteria andCommentAddressLike(String value) {
            addCriterion("comment_address like", value, "commentAddress");
            return (Criteria) this;
        }

        public Criteria andCommentAddressNotLike(String value) {
            addCriterion("comment_address not like", value, "commentAddress");
            return (Criteria) this;
        }

        public Criteria andCommentAddressIn(List<String> values) {
            addCriterion("comment_address in", values, "commentAddress");
            return (Criteria) this;
        }

        public Criteria andCommentAddressNotIn(List<String> values) {
            addCriterion("comment_address not in", values, "commentAddress");
            return (Criteria) this;
        }

        public Criteria andCommentAddressBetween(String value1, String value2) {
            addCriterion("comment_address between", value1, value2, "commentAddress");
            return (Criteria) this;
        }

        public Criteria andCommentAddressNotBetween(String value1, String value2) {
            addCriterion("comment_address not between", value1, value2, "commentAddress");
            return (Criteria) this;
        }

        public Criteria andCommentTelIsNull() {
            addCriterion("comment_tel is null");
            return (Criteria) this;
        }

        public Criteria andCommentTelIsNotNull() {
            addCriterion("comment_tel is not null");
            return (Criteria) this;
        }

        public Criteria andCommentTelEqualTo(String value) {
            addCriterion("comment_tel =", value, "commentTel");
            return (Criteria) this;
        }

        public Criteria andCommentTelNotEqualTo(String value) {
            addCriterion("comment_tel <>", value, "commentTel");
            return (Criteria) this;
        }

        public Criteria andCommentTelGreaterThan(String value) {
            addCriterion("comment_tel >", value, "commentTel");
            return (Criteria) this;
        }

        public Criteria andCommentTelGreaterThanOrEqualTo(String value) {
            addCriterion("comment_tel >=", value, "commentTel");
            return (Criteria) this;
        }

        public Criteria andCommentTelLessThan(String value) {
            addCriterion("comment_tel <", value, "commentTel");
            return (Criteria) this;
        }

        public Criteria andCommentTelLessThanOrEqualTo(String value) {
            addCriterion("comment_tel <=", value, "commentTel");
            return (Criteria) this;
        }

        public Criteria andCommentTelLike(String value) {
            addCriterion("comment_tel like", value, "commentTel");
            return (Criteria) this;
        }

        public Criteria andCommentTelNotLike(String value) {
            addCriterion("comment_tel not like", value, "commentTel");
            return (Criteria) this;
        }

        public Criteria andCommentTelIn(List<String> values) {
            addCriterion("comment_tel in", values, "commentTel");
            return (Criteria) this;
        }

        public Criteria andCommentTelNotIn(List<String> values) {
            addCriterion("comment_tel not in", values, "commentTel");
            return (Criteria) this;
        }

        public Criteria andCommentTelBetween(String value1, String value2) {
            addCriterion("comment_tel between", value1, value2, "commentTel");
            return (Criteria) this;
        }

        public Criteria andCommentTelNotBetween(String value1, String value2) {
            addCriterion("comment_tel not between", value1, value2, "commentTel");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cl_comment
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cl_comment
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}