package com.jia.changle.po;

import java.util.Date;

public class ClNews {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_news.news_id
     *
     * @mbggenerated
     */
    private Integer newsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_news.news_url
     *
     * @mbggenerated
     */
    private String newsUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_news.news_title_en
     *
     * @mbggenerated
     */
    private String newsTitleEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_news.news_title
     *
     * @mbggenerated
     */
    private String newsTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_news.news_subtitle_en
     *
     * @mbggenerated
     */
    private String newsSubtitleEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_news.news_subtitle
     *
     * @mbggenerated
     */
    private String newsSubtitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_news.news_content_en
     *
     * @mbggenerated
     */
    private String newsContentEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_news.news_count
     *
     * @mbggenerated
     */
    private Integer newsCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_news.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_news.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_news.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_news.news_content
     *
     * @mbggenerated
     */
    private String newsContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_news.news_id
     *
     * @return the value of cl_news.news_id
     *
     * @mbggenerated
     */
    public Integer getNewsId() {
        return newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_news.news_id
     *
     * @param newsId the value for cl_news.news_id
     *
     * @mbggenerated
     */
    public void setNewsId(Integer newsId) {
        this.newsId = newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_news.news_url
     *
     * @return the value of cl_news.news_url
     *
     * @mbggenerated
     */
    public String getNewsUrl() {
        return newsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_news.news_url
     *
     * @param newsUrl the value for cl_news.news_url
     *
     * @mbggenerated
     */
    public void setNewsUrl(String newsUrl) {
        this.newsUrl = newsUrl == null ? null : newsUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_news.news_title_en
     *
     * @return the value of cl_news.news_title_en
     *
     * @mbggenerated
     */
    public String getNewsTitleEn() {
        return newsTitleEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_news.news_title_en
     *
     * @param newsTitleEn the value for cl_news.news_title_en
     *
     * @mbggenerated
     */
    public void setNewsTitleEn(String newsTitleEn) {
        this.newsTitleEn = newsTitleEn == null ? null : newsTitleEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_news.news_title
     *
     * @return the value of cl_news.news_title
     *
     * @mbggenerated
     */
    public String getNewsTitle() {
        return newsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_news.news_title
     *
     * @param newsTitle the value for cl_news.news_title
     *
     * @mbggenerated
     */
    public void setNewsTitle(String newsTitle) {
        this.newsTitle = newsTitle == null ? null : newsTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_news.news_subtitle_en
     *
     * @return the value of cl_news.news_subtitle_en
     *
     * @mbggenerated
     */
    public String getNewsSubtitleEn() {
        return newsSubtitleEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_news.news_subtitle_en
     *
     * @param newsSubtitleEn the value for cl_news.news_subtitle_en
     *
     * @mbggenerated
     */
    public void setNewsSubtitleEn(String newsSubtitleEn) {
        this.newsSubtitleEn = newsSubtitleEn == null ? null : newsSubtitleEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_news.news_subtitle
     *
     * @return the value of cl_news.news_subtitle
     *
     * @mbggenerated
     */
    public String getNewsSubtitle() {
        return newsSubtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_news.news_subtitle
     *
     * @param newsSubtitle the value for cl_news.news_subtitle
     *
     * @mbggenerated
     */
    public void setNewsSubtitle(String newsSubtitle) {
        this.newsSubtitle = newsSubtitle == null ? null : newsSubtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_news.news_content_en
     *
     * @return the value of cl_news.news_content_en
     *
     * @mbggenerated
     */
    public String getNewsContentEn() {
        return newsContentEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_news.news_content_en
     *
     * @param newsContentEn the value for cl_news.news_content_en
     *
     * @mbggenerated
     */
    public void setNewsContentEn(String newsContentEn) {
        this.newsContentEn = newsContentEn == null ? null : newsContentEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_news.news_count
     *
     * @return the value of cl_news.news_count
     *
     * @mbggenerated
     */
    public Integer getNewsCount() {
        return newsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_news.news_count
     *
     * @param newsCount the value for cl_news.news_count
     *
     * @mbggenerated
     */
    public void setNewsCount(Integer newsCount) {
        this.newsCount = newsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_news.status
     *
     * @return the value of cl_news.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_news.status
     *
     * @param status the value for cl_news.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_news.update_time
     *
     * @return the value of cl_news.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_news.update_time
     *
     * @param updateTime the value for cl_news.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_news.create_time
     *
     * @return the value of cl_news.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_news.create_time
     *
     * @param createTime the value for cl_news.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_news.news_content
     *
     * @return the value of cl_news.news_content
     *
     * @mbggenerated
     */
    public String getNewsContent() {
        return newsContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_news.news_content
     *
     * @param newsContent the value for cl_news.news_content
     *
     * @mbggenerated
     */
    public void setNewsContent(String newsContent) {
        this.newsContent = newsContent == null ? null : newsContent.trim();
    }
}