package com.jia.changle.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ClNewsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cl_news
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cl_news
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cl_news
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_news
     *
     * @mbggenerated
     */
    public ClNewsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_news
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_news
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_news
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_news
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_news
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_news
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_news
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_news
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_news
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_news
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cl_news
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNewsIdIsNull() {
            addCriterion("news_id is null");
            return (Criteria) this;
        }

        public Criteria andNewsIdIsNotNull() {
            addCriterion("news_id is not null");
            return (Criteria) this;
        }

        public Criteria andNewsIdEqualTo(Integer value) {
            addCriterion("news_id =", value, "newsId");
            return (Criteria) this;
        }

        public Criteria andNewsIdNotEqualTo(Integer value) {
            addCriterion("news_id <>", value, "newsId");
            return (Criteria) this;
        }

        public Criteria andNewsIdGreaterThan(Integer value) {
            addCriterion("news_id >", value, "newsId");
            return (Criteria) this;
        }

        public Criteria andNewsIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("news_id >=", value, "newsId");
            return (Criteria) this;
        }

        public Criteria andNewsIdLessThan(Integer value) {
            addCriterion("news_id <", value, "newsId");
            return (Criteria) this;
        }

        public Criteria andNewsIdLessThanOrEqualTo(Integer value) {
            addCriterion("news_id <=", value, "newsId");
            return (Criteria) this;
        }

        public Criteria andNewsIdIn(List<Integer> values) {
            addCriterion("news_id in", values, "newsId");
            return (Criteria) this;
        }

        public Criteria andNewsIdNotIn(List<Integer> values) {
            addCriterion("news_id not in", values, "newsId");
            return (Criteria) this;
        }

        public Criteria andNewsIdBetween(Integer value1, Integer value2) {
            addCriterion("news_id between", value1, value2, "newsId");
            return (Criteria) this;
        }

        public Criteria andNewsIdNotBetween(Integer value1, Integer value2) {
            addCriterion("news_id not between", value1, value2, "newsId");
            return (Criteria) this;
        }

        public Criteria andNewsUrlIsNull() {
            addCriterion("news_url is null");
            return (Criteria) this;
        }

        public Criteria andNewsUrlIsNotNull() {
            addCriterion("news_url is not null");
            return (Criteria) this;
        }

        public Criteria andNewsUrlEqualTo(String value) {
            addCriterion("news_url =", value, "newsUrl");
            return (Criteria) this;
        }

        public Criteria andNewsUrlNotEqualTo(String value) {
            addCriterion("news_url <>", value, "newsUrl");
            return (Criteria) this;
        }

        public Criteria andNewsUrlGreaterThan(String value) {
            addCriterion("news_url >", value, "newsUrl");
            return (Criteria) this;
        }

        public Criteria andNewsUrlGreaterThanOrEqualTo(String value) {
            addCriterion("news_url >=", value, "newsUrl");
            return (Criteria) this;
        }

        public Criteria andNewsUrlLessThan(String value) {
            addCriterion("news_url <", value, "newsUrl");
            return (Criteria) this;
        }

        public Criteria andNewsUrlLessThanOrEqualTo(String value) {
            addCriterion("news_url <=", value, "newsUrl");
            return (Criteria) this;
        }

        public Criteria andNewsUrlLike(String value) {
            addCriterion("news_url like", value, "newsUrl");
            return (Criteria) this;
        }

        public Criteria andNewsUrlNotLike(String value) {
            addCriterion("news_url not like", value, "newsUrl");
            return (Criteria) this;
        }

        public Criteria andNewsUrlIn(List<String> values) {
            addCriterion("news_url in", values, "newsUrl");
            return (Criteria) this;
        }

        public Criteria andNewsUrlNotIn(List<String> values) {
            addCriterion("news_url not in", values, "newsUrl");
            return (Criteria) this;
        }

        public Criteria andNewsUrlBetween(String value1, String value2) {
            addCriterion("news_url between", value1, value2, "newsUrl");
            return (Criteria) this;
        }

        public Criteria andNewsUrlNotBetween(String value1, String value2) {
            addCriterion("news_url not between", value1, value2, "newsUrl");
            return (Criteria) this;
        }

        public Criteria andNewsTitleEnIsNull() {
            addCriterion("news_title_en is null");
            return (Criteria) this;
        }

        public Criteria andNewsTitleEnIsNotNull() {
            addCriterion("news_title_en is not null");
            return (Criteria) this;
        }

        public Criteria andNewsTitleEnEqualTo(String value) {
            addCriterion("news_title_en =", value, "newsTitleEn");
            return (Criteria) this;
        }

        public Criteria andNewsTitleEnNotEqualTo(String value) {
            addCriterion("news_title_en <>", value, "newsTitleEn");
            return (Criteria) this;
        }

        public Criteria andNewsTitleEnGreaterThan(String value) {
            addCriterion("news_title_en >", value, "newsTitleEn");
            return (Criteria) this;
        }

        public Criteria andNewsTitleEnGreaterThanOrEqualTo(String value) {
            addCriterion("news_title_en >=", value, "newsTitleEn");
            return (Criteria) this;
        }

        public Criteria andNewsTitleEnLessThan(String value) {
            addCriterion("news_title_en <", value, "newsTitleEn");
            return (Criteria) this;
        }

        public Criteria andNewsTitleEnLessThanOrEqualTo(String value) {
            addCriterion("news_title_en <=", value, "newsTitleEn");
            return (Criteria) this;
        }

        public Criteria andNewsTitleEnLike(String value) {
            addCriterion("news_title_en like", value, "newsTitleEn");
            return (Criteria) this;
        }

        public Criteria andNewsTitleEnNotLike(String value) {
            addCriterion("news_title_en not like", value, "newsTitleEn");
            return (Criteria) this;
        }

        public Criteria andNewsTitleEnIn(List<String> values) {
            addCriterion("news_title_en in", values, "newsTitleEn");
            return (Criteria) this;
        }

        public Criteria andNewsTitleEnNotIn(List<String> values) {
            addCriterion("news_title_en not in", values, "newsTitleEn");
            return (Criteria) this;
        }

        public Criteria andNewsTitleEnBetween(String value1, String value2) {
            addCriterion("news_title_en between", value1, value2, "newsTitleEn");
            return (Criteria) this;
        }

        public Criteria andNewsTitleEnNotBetween(String value1, String value2) {
            addCriterion("news_title_en not between", value1, value2, "newsTitleEn");
            return (Criteria) this;
        }

        public Criteria andNewsTitleIsNull() {
            addCriterion("news_title is null");
            return (Criteria) this;
        }

        public Criteria andNewsTitleIsNotNull() {
            addCriterion("news_title is not null");
            return (Criteria) this;
        }

        public Criteria andNewsTitleEqualTo(String value) {
            addCriterion("news_title =", value, "newsTitle");
            return (Criteria) this;
        }

        public Criteria andNewsTitleNotEqualTo(String value) {
            addCriterion("news_title <>", value, "newsTitle");
            return (Criteria) this;
        }

        public Criteria andNewsTitleGreaterThan(String value) {
            addCriterion("news_title >", value, "newsTitle");
            return (Criteria) this;
        }

        public Criteria andNewsTitleGreaterThanOrEqualTo(String value) {
            addCriterion("news_title >=", value, "newsTitle");
            return (Criteria) this;
        }

        public Criteria andNewsTitleLessThan(String value) {
            addCriterion("news_title <", value, "newsTitle");
            return (Criteria) this;
        }

        public Criteria andNewsTitleLessThanOrEqualTo(String value) {
            addCriterion("news_title <=", value, "newsTitle");
            return (Criteria) this;
        }

        public Criteria andNewsTitleLike(String value) {
            addCriterion("news_title like", value, "newsTitle");
            return (Criteria) this;
        }

        public Criteria andNewsTitleNotLike(String value) {
            addCriterion("news_title not like", value, "newsTitle");
            return (Criteria) this;
        }

        public Criteria andNewsTitleIn(List<String> values) {
            addCriterion("news_title in", values, "newsTitle");
            return (Criteria) this;
        }

        public Criteria andNewsTitleNotIn(List<String> values) {
            addCriterion("news_title not in", values, "newsTitle");
            return (Criteria) this;
        }

        public Criteria andNewsTitleBetween(String value1, String value2) {
            addCriterion("news_title between", value1, value2, "newsTitle");
            return (Criteria) this;
        }

        public Criteria andNewsTitleNotBetween(String value1, String value2) {
            addCriterion("news_title not between", value1, value2, "newsTitle");
            return (Criteria) this;
        }

        public Criteria andNewsSubtitleEnIsNull() {
            addCriterion("news_subtitle_en is null");
            return (Criteria) this;
        }

        public Criteria andNewsSubtitleEnIsNotNull() {
            addCriterion("news_subtitle_en is not null");
            return (Criteria) this;
        }

        public Criteria andNewsSubtitleEnEqualTo(String value) {
            addCriterion("news_subtitle_en =", value, "newsSubtitleEn");
            return (Criteria) this;
        }

        public Criteria andNewsSubtitleEnNotEqualTo(String value) {
            addCriterion("news_subtitle_en <>", value, "newsSubtitleEn");
            return (Criteria) this;
        }

        public Criteria andNewsSubtitleEnGreaterThan(String value) {
            addCriterion("news_subtitle_en >", value, "newsSubtitleEn");
            return (Criteria) this;
        }

        public Criteria andNewsSubtitleEnGreaterThanOrEqualTo(String value) {
            addCriterion("news_subtitle_en >=", value, "newsSubtitleEn");
            return (Criteria) this;
        }

        public Criteria andNewsSubtitleEnLessThan(String value) {
            addCriterion("news_subtitle_en <", value, "newsSubtitleEn");
            return (Criteria) this;
        }

        public Criteria andNewsSubtitleEnLessThanOrEqualTo(String value) {
            addCriterion("news_subtitle_en <=", value, "newsSubtitleEn");
            return (Criteria) this;
        }

        public Criteria andNewsSubtitleEnLike(String value) {
            addCriterion("news_subtitle_en like", value, "newsSubtitleEn");
            return (Criteria) this;
        }

        public Criteria andNewsSubtitleEnNotLike(String value) {
            addCriterion("news_subtitle_en not like", value, "newsSubtitleEn");
            return (Criteria) this;
        }

        public Criteria andNewsSubtitleEnIn(List<String> values) {
            addCriterion("news_subtitle_en in", values, "newsSubtitleEn");
            return (Criteria) this;
        }

        public Criteria andNewsSubtitleEnNotIn(List<String> values) {
            addCriterion("news_subtitle_en not in", values, "newsSubtitleEn");
            return (Criteria) this;
        }

        public Criteria andNewsSubtitleEnBetween(String value1, String value2) {
            addCriterion("news_subtitle_en between", value1, value2, "newsSubtitleEn");
            return (Criteria) this;
        }

        public Criteria andNewsSubtitleEnNotBetween(String value1, String value2) {
            addCriterion("news_subtitle_en not between", value1, value2, "newsSubtitleEn");
            return (Criteria) this;
        }

        public Criteria andNewsSubtitleIsNull() {
            addCriterion("news_subtitle is null");
            return (Criteria) this;
        }

        public Criteria andNewsSubtitleIsNotNull() {
            addCriterion("news_subtitle is not null");
            return (Criteria) this;
        }

        public Criteria andNewsSubtitleEqualTo(String value) {
            addCriterion("news_subtitle =", value, "newsSubtitle");
            return (Criteria) this;
        }

        public Criteria andNewsSubtitleNotEqualTo(String value) {
            addCriterion("news_subtitle <>", value, "newsSubtitle");
            return (Criteria) this;
        }

        public Criteria andNewsSubtitleGreaterThan(String value) {
            addCriterion("news_subtitle >", value, "newsSubtitle");
            return (Criteria) this;
        }

        public Criteria andNewsSubtitleGreaterThanOrEqualTo(String value) {
            addCriterion("news_subtitle >=", value, "newsSubtitle");
            return (Criteria) this;
        }

        public Criteria andNewsSubtitleLessThan(String value) {
            addCriterion("news_subtitle <", value, "newsSubtitle");
            return (Criteria) this;
        }

        public Criteria andNewsSubtitleLessThanOrEqualTo(String value) {
            addCriterion("news_subtitle <=", value, "newsSubtitle");
            return (Criteria) this;
        }

        public Criteria andNewsSubtitleLike(String value) {
            addCriterion("news_subtitle like", value, "newsSubtitle");
            return (Criteria) this;
        }

        public Criteria andNewsSubtitleNotLike(String value) {
            addCriterion("news_subtitle not like", value, "newsSubtitle");
            return (Criteria) this;
        }

        public Criteria andNewsSubtitleIn(List<String> values) {
            addCriterion("news_subtitle in", values, "newsSubtitle");
            return (Criteria) this;
        }

        public Criteria andNewsSubtitleNotIn(List<String> values) {
            addCriterion("news_subtitle not in", values, "newsSubtitle");
            return (Criteria) this;
        }

        public Criteria andNewsSubtitleBetween(String value1, String value2) {
            addCriterion("news_subtitle between", value1, value2, "newsSubtitle");
            return (Criteria) this;
        }

        public Criteria andNewsSubtitleNotBetween(String value1, String value2) {
            addCriterion("news_subtitle not between", value1, value2, "newsSubtitle");
            return (Criteria) this;
        }

        public Criteria andNewsContentEnIsNull() {
            addCriterion("news_content_en is null");
            return (Criteria) this;
        }

        public Criteria andNewsContentEnIsNotNull() {
            addCriterion("news_content_en is not null");
            return (Criteria) this;
        }

        public Criteria andNewsContentEnEqualTo(String value) {
            addCriterion("news_content_en =", value, "newsContentEn");
            return (Criteria) this;
        }

        public Criteria andNewsContentEnNotEqualTo(String value) {
            addCriterion("news_content_en <>", value, "newsContentEn");
            return (Criteria) this;
        }

        public Criteria andNewsContentEnGreaterThan(String value) {
            addCriterion("news_content_en >", value, "newsContentEn");
            return (Criteria) this;
        }

        public Criteria andNewsContentEnGreaterThanOrEqualTo(String value) {
            addCriterion("news_content_en >=", value, "newsContentEn");
            return (Criteria) this;
        }

        public Criteria andNewsContentEnLessThan(String value) {
            addCriterion("news_content_en <", value, "newsContentEn");
            return (Criteria) this;
        }

        public Criteria andNewsContentEnLessThanOrEqualTo(String value) {
            addCriterion("news_content_en <=", value, "newsContentEn");
            return (Criteria) this;
        }

        public Criteria andNewsContentEnLike(String value) {
            addCriterion("news_content_en like", value, "newsContentEn");
            return (Criteria) this;
        }

        public Criteria andNewsContentEnNotLike(String value) {
            addCriterion("news_content_en not like", value, "newsContentEn");
            return (Criteria) this;
        }

        public Criteria andNewsContentEnIn(List<String> values) {
            addCriterion("news_content_en in", values, "newsContentEn");
            return (Criteria) this;
        }

        public Criteria andNewsContentEnNotIn(List<String> values) {
            addCriterion("news_content_en not in", values, "newsContentEn");
            return (Criteria) this;
        }

        public Criteria andNewsContentEnBetween(String value1, String value2) {
            addCriterion("news_content_en between", value1, value2, "newsContentEn");
            return (Criteria) this;
        }

        public Criteria andNewsContentEnNotBetween(String value1, String value2) {
            addCriterion("news_content_en not between", value1, value2, "newsContentEn");
            return (Criteria) this;
        }

        public Criteria andNewsCountIsNull() {
            addCriterion("news_count is null");
            return (Criteria) this;
        }

        public Criteria andNewsCountIsNotNull() {
            addCriterion("news_count is not null");
            return (Criteria) this;
        }

        public Criteria andNewsCountEqualTo(Integer value) {
            addCriterion("news_count =", value, "newsCount");
            return (Criteria) this;
        }

        public Criteria andNewsCountNotEqualTo(Integer value) {
            addCriterion("news_count <>", value, "newsCount");
            return (Criteria) this;
        }

        public Criteria andNewsCountGreaterThan(Integer value) {
            addCriterion("news_count >", value, "newsCount");
            return (Criteria) this;
        }

        public Criteria andNewsCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("news_count >=", value, "newsCount");
            return (Criteria) this;
        }

        public Criteria andNewsCountLessThan(Integer value) {
            addCriterion("news_count <", value, "newsCount");
            return (Criteria) this;
        }

        public Criteria andNewsCountLessThanOrEqualTo(Integer value) {
            addCriterion("news_count <=", value, "newsCount");
            return (Criteria) this;
        }

        public Criteria andNewsCountIn(List<Integer> values) {
            addCriterion("news_count in", values, "newsCount");
            return (Criteria) this;
        }

        public Criteria andNewsCountNotIn(List<Integer> values) {
            addCriterion("news_count not in", values, "newsCount");
            return (Criteria) this;
        }

        public Criteria andNewsCountBetween(Integer value1, Integer value2) {
            addCriterion("news_count between", value1, value2, "newsCount");
            return (Criteria) this;
        }

        public Criteria andNewsCountNotBetween(Integer value1, Integer value2) {
            addCriterion("news_count not between", value1, value2, "newsCount");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cl_news
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cl_news
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}