package com.jia.changle.po;

import java.util.Date;

public class ClProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_product.product_id
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_product.product_name
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_product.product_description
     *
     * @mbggenerated
     */
    private String productDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_product.product_img
     *
     * @mbggenerated
     */
    private String productImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_product.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_product.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_product.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_product.product_name_en
     *
     * @mbggenerated
     */
    private String productNameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_product.product_description_en
     *
     * @mbggenerated
     */
    private String productDescriptionEn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_product.product_id
     *
     * @return the value of cl_product.product_id
     *
     * @mbggenerated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_product.product_id
     *
     * @param productId the value for cl_product.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_product.product_name
     *
     * @return the value of cl_product.product_name
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_product.product_name
     *
     * @param productName the value for cl_product.product_name
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_product.product_description
     *
     * @return the value of cl_product.product_description
     *
     * @mbggenerated
     */
    public String getProductDescription() {
        return productDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_product.product_description
     *
     * @param productDescription the value for cl_product.product_description
     *
     * @mbggenerated
     */
    public void setProductDescription(String productDescription) {
        this.productDescription = productDescription == null ? null : productDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_product.product_img
     *
     * @return the value of cl_product.product_img
     *
     * @mbggenerated
     */
    public String getProductImg() {
        return productImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_product.product_img
     *
     * @param productImg the value for cl_product.product_img
     *
     * @mbggenerated
     */
    public void setProductImg(String productImg) {
        this.productImg = productImg == null ? null : productImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_product.status
     *
     * @return the value of cl_product.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_product.status
     *
     * @param status the value for cl_product.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_product.update_time
     *
     * @return the value of cl_product.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_product.update_time
     *
     * @param updateTime the value for cl_product.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_product.create_time
     *
     * @return the value of cl_product.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_product.create_time
     *
     * @param createTime the value for cl_product.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_product.product_name_en
     *
     * @return the value of cl_product.product_name_en
     *
     * @mbggenerated
     */
    public String getProductNameEn() {
        return productNameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_product.product_name_en
     *
     * @param productNameEn the value for cl_product.product_name_en
     *
     * @mbggenerated
     */
    public void setProductNameEn(String productNameEn) {
        this.productNameEn = productNameEn == null ? null : productNameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_product.product_description_en
     *
     * @return the value of cl_product.product_description_en
     *
     * @mbggenerated
     */
    public String getProductDescriptionEn() {
        return productDescriptionEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_product.product_description_en
     *
     * @param productDescriptionEn the value for cl_product.product_description_en
     *
     * @mbggenerated
     */
    public void setProductDescriptionEn(String productDescriptionEn) {
        this.productDescriptionEn = productDescriptionEn == null ? null : productDescriptionEn.trim();
    }
}