package com.jia.changle.mapper;

import com.jia.changle.po.ClComment;
import com.jia.changle.po.ClCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_comment
     *
     * @mbggenerated
     */
    int countByExample(ClCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_comment
     *
     * @mbggenerated
     */
    int deleteByExample(ClCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_comment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_comment
     *
     * @mbggenerated
     */
    int insert(ClComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_comment
     *
     * @mbggenerated
     */
    int insertSelective(ClComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_comment
     *
     * @mbggenerated
     */
    List<ClComment> selectByExampleWithBLOBs(ClCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_comment
     *
     * @mbggenerated
     */
    List<ClComment> selectByExample(ClCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_comment
     *
     * @mbggenerated
     */
    ClComment selectByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_comment
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ClComment record, @Param("example") ClCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_comment
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") ClComment record, @Param("example") ClCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_comment
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ClComment record, @Param("example") ClCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ClComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ClComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ClComment record);
}