package com.jia.changle.mapper;

import com.jia.changle.po.ClNews;
import com.jia.changle.po.ClNewsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClNewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_news
     *
     * @mbggenerated
     */
    int countByExample(ClNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_news
     *
     * @mbggenerated
     */
    int deleteByExample(ClNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_news
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer newsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_news
     *
     * @mbggenerated
     */
    int insert(ClNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_news
     *
     * @mbggenerated
     */
    int insertSelective(ClNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_news
     *
     * @mbggenerated
     */
    List<ClNews> selectByExampleWithBLOBs(ClNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_news
     *
     * @mbggenerated
     */
    List<ClNews> selectByExample(ClNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_news
     *
     * @mbggenerated
     */
    ClNews selectByPrimaryKey(Integer newsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_news
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ClNews record, @Param("example") ClNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_news
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") ClNews record, @Param("example") ClNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_news
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ClNews record, @Param("example") ClNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_news
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ClNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_news
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ClNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_news
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ClNews record);
}