package com.jia.changle.mapper;

import com.jia.changle.po.ClUser;
import com.jia.changle.po.ClUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user
     *
     * @mbggenerated
     */
    int countByExample(ClUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user
     *
     * @mbggenerated
     */
    int deleteByExample(ClUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user
     *
     * @mbggenerated
     */
    int insert(ClUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user
     *
     * @mbggenerated
     */
    int insertSelective(ClUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user
     *
     * @mbggenerated
     */
    List<ClUser> selectByExample(ClUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user
     *
     * @mbggenerated
     */
    ClUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ClUser record, @Param("example") ClUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ClUser record, @Param("example") ClUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ClUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ClUser record);
}